package com.amaral.driverlab;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.Test;

public final class ReportLanguageTest {
    @Test
    public void portugueseIsUsedOnlyForPortugueseAppLocales() {
        assertTrue(ReportLanguage.isPortuguese("pt-BR"));
        assertTrue(ReportLanguage.isPortuguese("pt-PT"));
        assertFalse(ReportLanguage.isPortuguese("en-US"));
        assertFalse(ReportLanguage.isPortuguese("es"));
        assertFalse(ReportLanguage.isPortuguese("de-DE"));
        assertFalse(ReportLanguage.isPortuguese(null));
    }

    @Test
    public void fullResultMarkdownIsEnglishForEveryNonPortugueseLocale() throws Exception {
        JSONObject manifest = manifest();
        String english = GitHubIssuePublisher.qualificationIssueBody("en-US", manifest, false);
        String spanishApp = GitHubIssuePublisher.qualificationIssueBody("es", manifest, false);

        assertTrue(english.contains("### Execution summary"));
        assertTrue(english.contains("### Driver identity — do not confuse the roles"));
        assertTrue(english.contains("Candidate driver not recommended"));
        assertTrue(english.contains("Advanced scene: GPU Stress 3D 720p"));
        assertTrue(english.contains("_Generated by Amaral Driver Lab"));
        assertFalse(english.contains("Resumo da execução"));
        assertFalse(english.contains("DRIVER CANDIDATO"));
        assertEquals(english, spanishApp);
    }

    @Test
    public void portugueseFullResultRemainsUnchanged() throws Exception {
        String portuguese = GitHubIssuePublisher.qualificationIssueBody(
                "pt-BR", manifest(), false);

        assertTrue(portuguese.contains("### Resumo da execução"));
        assertTrue(portuguese.contains("### Identidade dos drivers"));
        assertTrue(portuguese.contains("Driver candidato não recomendado"));
        assertTrue(portuguese.contains("_Gerado por Amaral Driver Lab"));
    }

    @Test
    public void technicalLimitationsUseEnglishOutsidePortugueseLocales() {
        String portuguese = "Métrica sintética; não representa um jogo completo.";
        assertEquals(portuguese, ReportLanguage.limitation("pt-BR", portuguese));
        assertTrue(ReportLanguage.limitation("de", portuguese)
                .startsWith("Results are valid only"));
        assertFalse(ReportLanguage.limitation("de", portuguese).contains("Métrica"));
    }

    private static JSONObject manifest() throws Exception {
        JSONObject metric = new JSONObject()
                .put("step_id", "visual_gpu_stress")
                .put("label", "Cena avançada: GPU Stress 3D 720p")
                .put("kind", "performance")
                .put("unit", "ms")
                .put("lower_is_better", true)
                .put("reference", new JSONObject().put("median", 10.0))
                .put("candidate", new JSONObject().put("median", 11.0))
                .put("absolute_difference", 1.0)
                .put("candidate_improvement_percent", -10.0)
                .put("classification", "candidate_worse")
                .put("winner", "reference");
        JSONObject optimization = new JSONObject()
                .put("hardware_target", new JSONObject()
                        .put("console", "RedMagic 11 Pro")
                        .put("gpu_model", "Adreno 840"))
                .put("metrics", new JSONArray().put(metric))
                .put("loader_audit", new JSONArray())
                .put("best_area", metric)
                .put("worst_area", metric);
        JSONObject score = new JSONObject()
                .put("overall_index", 50)
                .put("performance_index", 50)
                .put("compatibility_index", 50)
                .put("weighted_improvement_percent", -10)
                .put("confidence", "low")
                .put("gate_reasons", new JSONArray());
        JSONObject human = new JSONObject()
                .put("headline", "Driver candidato não recomendado")
                .put("detail", "Falhas de compatibilidade, validade ou cobertura impediram uma recomendação.");
        return new JSONObject()
                .put("qualification_id", "qualification-test")
                .put("comparison_mode", "system_vs_turnip")
                .put("driver", new JSONObject()
                        .put("name", "Candidate")
                        .put("packageVersion", "v1")
                        .put("sha256", "candidate-sha"))
                .put("execution", new JSONObject()
                        .put("state", "completed")
                        .put("steps", new JSONArray()))
                .put("report", new JSONObject()
                        .put("hardware_identity", new JSONObject()
                                .put("model", "RedMagic 11 Pro")
                                .put("gpu_model", "Adreno 840"))
                        .put("score", score)
                        .put("human_summary", human)
                        .put("optimization_report", optimization));
    }
}
